import * as React from 'react';
declare type CheckBoxProps = {
    Component?: JSX.Element;
    iconRight?: boolean;
    title?: string | JSX.Element;
    titleProps?: object;
    center?: boolean;
    right?: boolean;
    containerStyle?: any;
    wrapperStyle?: any;
    textStyle?: any;
    onPress?: (...args: any[]) => any;
    onLongPress?: (...args: any[]) => any;
    checkedTitle?: string;
    fontFamily?: string;
};
declare const CheckBox: React.SFC<CheckBoxProps>;
export { CheckBox };
declare const _default: any;
export default _default;
