import React from 'react';
declare type IconProps = {
    type?: string;
    name?: string;
    size?: number;
    color?: string;
    Component?: JSX.Element;
    underlayColor?: string;
    reverse?: boolean;
    raised?: boolean;
    containerStyle?: any;
    iconStyle?: any;
    onPress?: (...args: any[]) => any;
    reverseColor?: string;
    disabled?: boolean;
    disabledStyle?: any;
    solid?: boolean;
    brand?: boolean;
};
declare const Icon: React.SFC<IconProps>;
export { Icon };
declare const _default: any;
export default _default;
