import * as React from 'react';
declare type FeaturedTileProps = {
    title?: string;
    icon?: object;
    caption?: React.ReactNode;
    imageSrc?: any;
    onPress?: (...args: any[]) => any;
    containerStyle?: any;
    iconContainerStyle?: any;
    imageContainerStyle?: any;
    overlayContainerStyle?: any;
    titleStyle?: any;
    captionStyle?: any;
    width?: number;
    height?: number;
    ImageComponent?: React.ReactNode;
    imageProps?: object;
};
declare const FeaturedTile: React.SFC<FeaturedTileProps>;
export { FeaturedTile };
declare const _default: any;
export default _default;
