import * as React from 'react';
declare type AvatarProps = {
    Component?: any;
    onPress?: (...args: any[]) => any;
    onLongPress?: (...args: any[]) => any;
    containerStyle?: any;
    source?: any;
    avatarStyle?: any;
    rounded?: boolean;
    title?: string;
    titleStyle?: any;
    overlayContainerStyle?: any;
    activeOpacity?: number;
    icon?: object;
    iconStyle?: any;
    size?: ('small' | 'medium' | 'large' | 'xlarge') | number;
    showEditButton?: boolean;
    onEditPress?: (...args: any[]) => any;
    editButton?: {
        size?: number;
        name?: string;
        type?: string;
        color?: string;
        underlayColor?: string;
        style?: any;
    };
    placeholderStyle?: any;
    renderPlaceholderContent?: any;
    imageProps?: object;
    ImageComponent?: React.ReactNode;
};
declare const Avatar: React.SFC<AvatarProps>;
export { Avatar };
declare const _default: any;
export default _default;
