import React from 'react';
declare type CardProps = {
    containerStyle?: any;
    wrapperStyle?: any;
    overlayStyle?: any;
    title?: string | JSX.Element;
    titleStyle?: any;
    featuredTitle?: string;
    featuredTitleStyle?: any;
    featuredSubtitle?: string;
    featuredSubtitleStyle?: any;
    dividerStyle?: any;
    image?: any;
    imageStyle?: any;
    imageWrapperStyle?: any;
    imageProps?: object;
    titleNumberOfLines?: number;
    theme?: object;
};
declare const Card: React.SFC<CardProps>;
export { Card };
declare const _default: any;
export default _default;
