import * as React from 'react';
declare type ButtonGroupProps = {
    button?: object;
    Component?: React.ReactNode;
    onPress?: (...args: any[]) => any;
    buttons?: any[];
    containerStyle?: any;
    textStyle?: any;
    selectedTextStyle?: any;
    selectedButtonStyle?: any;
    underlayColor?: string;
    selectedIndex?: number;
    selectedIndexes?: number[];
    activeOpacity?: number;
    onHideUnderlay?: (...args: any[]) => any;
    onShowUnderlay?: (...args: any[]) => any;
    setOpacityTo?: (...args: any[]) => any;
    innerBorderStyle?: {
        color?: string;
        width?: number;
    };
    lastBorderStyle?: any | any;
    buttonStyle?: any;
    selectMultiple?: boolean;
    theme?: object;
    disabled?: boolean | number[];
    disabledStyle?: any;
    disabledTextStyle?: any;
    disabledSelectedStyle?: any;
    disabledSelectedTextStyle?: any;
};
declare const ButtonGroup: React.SFC<ButtonGroupProps>;
export { ButtonGroup };
declare const _default: any;
export default _default;
